macos_instance:
  image: ghcr.io/cirruslabs/macos-monterey-base:latest

mac_task:
  script: brew install --cask docker; docker build . -t testdir1 -f dir1/Dockerfile

ubuntu22_spicy_task:
  container:
    dockerfile: dir1/Dockerfile
