name: debootstrap behavir in docker on different platforms

on:
  workflow_dispatch:

jobs:
  os_matrix:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Test debootstrap
        run: |
          mkdir test1
          cd test1
          echo "FROM ubuntu:latest" > Dockerfile
          echo "RUN apt update && apt install -y debootstrap" >> Dockerfile
          echo "RUN debootstrap "--variant=minbase" --arch armhf jammy /tmp/test1 http://ports.ubuntu.com/"
