name: debootstrap behavior in docker on different platforms

on:
  workflow_dispatch:

jobs:
  os_matrix:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Test debootstrap
        run: |
          mkdir test1
          cd test1
          echo "FROM --platform=linux/amd64 ubuntu:latest" > Dockerfile
          echo "RUN apt update && apt install -y debootstrap" >> Dockerfile
          echo "RUN debootstrap "--variant=minbase" --arch armhf jammy /tmp/test1 http://ports.ubuntu.com/"
          dir "C:\\Program Files\Docker\Docker\DockerCli.exe"
          docker build . -t test1
