name: debootstrap behavior in docker on different platforms

on:
  workflow_dispatch:

jobs:
  os_matrix:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Test debootstrap
        run: |
          mkdir test1
          cd test1
          echo "FROM --platform=linux/amd64 ubuntu:latest" > Dockerfile
          echo "RUN apt update && apt install -y debootstrap" >> Dockerfile
          echo "RUN debootstrap "--variant=minbase" --arch armhf jammy /tmp/test1 http://ports.ubuntu.com/"
          gcm docker
          wsl --update
          Invoke-WebRequest https://github.com/am11/VoidWSL/releases/download/24032100/void-x86_64-musl.zip -Out void-x86_64-musl.zip
          Expand-Archive .\void-x86_64-musl.zip .\void-linux
          void-linux\void-x86_64-musl.exe run uname -a
          #wsl --install -d openSUSE-Tumbleweed
          #wsl -e uname -a
          #choco install -y docker-for-windows
          #&"${env:ProgramFiles}\Docker\Docker\DockerCli.exe" -SwitchLinuxEngine
          #wsl -e docker build . -t test1
