name: debootstrap behavior in docker on different platforms

on:
  workflow_dispatch:

jobs:
  os_matrix:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Test debootstrap
        run: |
          #git clone https://github.com/am11/CrossRepoCITesting; cd CrossRepoCITesting/dir1; docker build --progress=plain -t dir1-testing .
          mkdir test1
          cd test1
          echo 'FROM --platform=linux/amd64 ubuntu:latest' > Dockerfile
          echo 'RUN apt update && apt install -y debootstrap libext2fs2 qemu-user-static' >> Dockerfile
          echo 'RUN debootstrap "--variant=minbase" --arch armhf jammy /tmp/test1 http://ports.ubuntu.com/ || true' >> Dockerfile
          #echo 'RUN cat /tmp/test1/debootstrap/debootstrap.log' >> Dockerfile
          docker build --progress=plain -t minbase-testing .
          sudo sh -c 'apt update && apt install -y debootstrap libext2fs2 qemu-user-static'
          sudo debootstrap "--variant=minbase" --arch armhf jammy /tmp/test1 http://ports.ubuntu.com/ || true
          cat /tmp/test1/debootstrap/debootstrap.log
          gcm docker
          wsl --update --web-download
          Invoke-WebRequest https://github.com/am11/VoidWSL/releases/download/24032100/void-x86_64-musl.zip -Out void-x86_64-musl.zip
          Expand-Archive .\void-x86_64-musl.zip .\void-linux
          echo command-start
          void-linux\void-x86_64-musl.exe run uname -a
          echo command-end
          #wsl --install -d openSUSE-Tumbleweed
          #wsl -e uname -a
          wsl --list --verbose
          #choco install -y docker-for-windows
          #&"${env:ProgramFiles}\Docker\Docker\DockerCli.exe" -SwitchLinuxEngine
          #wsl -e docker build . -t test1
