name: freebsd-x64 dotnet-runtime aot

on:
  workflow_dispatch:
    inputs:
      runtimeForkName:
        description: fork
        required: true
        default: dotnet
      runtimeBranchName:
        description: branch
        required: true
        default: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Maximize build space
      uses: AdityaGarg8/remove-unwanted-software@v4.1
      with:
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-cached-tools: 'true'

    - name: runtime, libs and nativeaot smoke tests build
      run: |
        git clone https://github.com/${{ github.event.inputs.runtimeForkName }}/runtime --branch ${{ github.event.inputs.runtimeBranchName }} --single-branch --depth 1

    - name: run tests in qemu
      uses: vmactions/freebsd-vm@v1
      env:
        CORE_ROOT: /home/runner/work/CrossRepoCITesting/CrossRepoCITesting/runtime/artifacts/tests/coreclr/freebsd.x64.Checked/Tests/Core_Root
      with:
        arch: x86_64
        envs: 'CORE_ROOT'
        usesh: true
        sync: nfs
        run: |
          pkg install -y llvm
          sudo mkdir -p $CORE_ROOT/SuperFileCheck/runtimes/freebsd-x64/native
          sudo ln -s /usr/local/bin/llvm-dwarfdump $CORE_ROOT/SuperFileCheck/runtimes/freebsd-x64/native
