name: illumos-x64 dotnet-runtime build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Test runtime build
      run: |
        git clone https://github.com/am11/runtime --single-branch --depth 1 --branch feature/build/illumos-fixes
        docker run --rm -v$(pwd)/runtime:/runtime -e ROOTFS_DIR=/crossrootfs/x64 \
          mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-cross-illumos-20220531132048-f13d79e \
          /runtime/build.sh libs.native -c Release -os illumos -cross -gcc
