name: illumos-x64 dotnet-runtime build

on:
  workflow_dispatch:
    inputs:
      runtimeForkName:
        description: fork
        required: true
        default: dotnet
      runtimeRepohName:
        description: repo
        required: true
        default: runtime
      runtimeBranchName:
        description: branch
        required: true
        default: main

jobs:
  coreclr_Debug:
    runs-on: ubuntu-latest

    steps:
    - name: Remove unnecessary files
      run: df -h; sudo rm -rf "$AGENT_TOOLSDIRECTORY"; df -h
    - name: runtime+libs+packs build
      run: |
        git clone https://github.com/${{ github.event.inputs.runtimeForkName }}/${{ github.event.inputs.runtimeRepohName }} runtime --branch ${{ github.event.inputs.runtimeBranchName }} --single-branch --depth 1
        git -C runtime rev-parse HEAD
        docker run --rm -v$(pwd)/runtime:/runtime -w /runtime -e ROOTFS_DIR=/crossrootfs/x64 -e SED_SCRIPT="$SED_SCRIPT" \
          mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-22.04-cross-illumos sh -c 'apt update --allow-insecure-repositories &&
          apt install -y ninja-build --allow-unauthenticated;
          /runtime/build.sh clr+libs+packs -c Release -os illumos -cross -gcc --restore;
          find ~/.nuget -name Version.targets | xargs wc -l;
          find ~/.nuget -name Version.targets -print0 | xargs -0 sed -i "$SED_SCRIPT";
          find ~/.nuget -name Version.targets | xargs wc -l;
          /runtime/build.sh clr+libs+packs -c Debug -os illumos -cross -gcc --bootstrap --build'

  coreclr_Release:
    runs-on: ubuntu-latest

    steps:
    - name: Remove unnecessary files
      run: df -h; sudo rm -rf "$AGENT_TOOLSDIRECTORY"; df -h
    - name: runtime+libs+packs build
      run: |
        git clone https://github.com/${{ github.event.inputs.runtimeForkName }}/${{ github.event.inputs.runtimeRepohName }} runtime --branch ${{ github.event.inputs.runtimeBranchName }} --single-branch --depth 1
        export SED_SCRIPT='s|static char sccsid\[\] __attribute__((used,retain)) = "@(#)Version $(FileVersion)$(_SourceBuildInfo)";|#if defined(__GNUC__) \&\& !defined(__clang__) \&\& defined(TARGET_SUNOS)\n#define RETAIN __attribute__((used))\n__asm__(".pushsection .init_array; .reloc ., R_X86_64_NONE, sccsid; .popsection");\n#else\n#define RETAIN __attribute__((used, retain))\n#endif\n\nstatic char sccsid[] RETAIN = "@(#)Version $(FileVersion)$(_SourceBuildInfo)";|g'
        docker run --rm -v$(pwd)/runtime:/runtime -w /runtime -e ROOTFS_DIR=/crossrootfs/x64 -e SED_SCRIPT="$SED_SCRIPT" \
          mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-22.04-cross-illumos sh -c 'apt update --allow-insecure-repositories &&
          apt install -y ninja-build --allow-unauthenticated;
          /runtime/build.sh clr+libs+packs -c Release -os illumos -cross -gcc --restore;
          find ~/.nuget -name Version.targets | xargs wc -l;
          find ~/.nuget -name Version.targets -print0 | xargs -0 sed -i "$SED_SCRIPT";
          find ~/.nuget -name Version.targets | xargs wc -l;
          /runtime/build.sh clr+libs+packs -c Release -os illumos -cross -gcc --bootstrap --build'

  mono_Debug:
    runs-on: ubuntu-latest

    steps:
    - name: Remove unnecessary files
      run: df -h; sudo rm -rf "$AGENT_TOOLSDIRECTORY"; df -h
    - name: runtime+libs+packs build
      run: |
        git clone https://github.com/${{ github.event.inputs.runtimeForkName }}/${{ github.event.inputs.runtimeRepohName }} runtime --branch ${{ github.event.inputs.runtimeBranchName }} --single-branch --depth 1
        export SED_SCRIPT='s|static char sccsid\[\] __attribute__((used,retain)) = "@(#)Version $(FileVersion)$(_SourceBuildInfo)";|#if defined(__GNUC__) \&\& !defined(__clang__) \&\& defined(TARGET_SUNOS)\n#define RETAIN __attribute__((used))\n__asm__(".pushsection .init_array; .reloc ., R_X86_64_NONE, sccsid; .popsection");\n#else\n#define RETAIN __attribute__((used, retain))\n#endif\n\nstatic char sccsid[] RETAIN = "@(#)Version $(FileVersion)$(_SourceBuildInfo)";|g'
        docker run --rm -v$(pwd)/runtime:/runtime -w /runtime -e ROOTFS_DIR=/crossrootfs/x64 -e SED_SCRIPT="$SED_SCRIPT" \
          mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-22.04-cross-illumos sh -c 'apt update --allow-insecure-repositories &&
          apt install -y ninja-build --allow-unauthenticated;
          /runtime/build.sh clr+libs+packs -c Release -os illumos -cross -gcc --restore;
          find ~/.nuget -name Version.targets | xargs wc -l;
          find ~/.nuget -name Version.targets -print0 | xargs -0 sed -i "$SED_SCRIPT";
          find ~/.nuget -name Version.targets | xargs wc -l;
          /runtime/build.sh mono+libs+packs -c Debug -os illumos -cross -gcc --build'

  mono_Release:
    runs-on: ubuntu-latest

    steps:
    - name: Remove unnecessary files
      run: df -h; sudo rm -rf "$AGENT_TOOLSDIRECTORY"; df -h
    - name: runtime+libs+packs build
      run: |
        git clone https://github.com/${{ github.event.inputs.runtimeForkName }}/${{ github.event.inputs.runtimeRepohName }} runtime --branch ${{ github.event.inputs.runtimeBranchName }} --single-branch --depth 1
        export SED_SCRIPT='s|static char sccsid\[\] __attribute__((used,retain)) = "@(#)Version $(FileVersion)$(_SourceBuildInfo)";|#if defined(__GNUC__) \&\& !defined(__clang__) \&\& defined(TARGET_SUNOS)\n#define RETAIN __attribute__((used))\n__asm__(".pushsection .init_array; .reloc ., R_X86_64_NONE, sccsid; .popsection");\n#else\n#define RETAIN __attribute__((used, retain))\n#endif\n\nstatic char sccsid[] RETAIN = "@(#)Version $(FileVersion)$(_SourceBuildInfo)";|g'
        docker run --rm -v$(pwd)/runtime:/runtime -w /runtime -e ROOTFS_DIR=/crossrootfs/x64 -e SED_SCRIPT="$SED_SCRIPT" \
          mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-22.04-cross-illumos sh -c 'apt update --allow-insecure-repositories &&
          apt install -y ninja-build --allow-unauthenticated;
          /runtime/build.sh clr+libs+packs -c Release -os illumos -cross -gcc --restore;
          find ~/.nuget -name Version.targets | xargs wc -l;
          find ~/.nuget -name Version.targets -print0 | xargs -0 sed -i "$SED_SCRIPT";
          find ~/.nuget -name Version.targets | xargs wc -l;
          /runtime/build.sh mono+libs+packs -c Release -os illumos -cross -gcc --build'
