name: JIT Diffs

on:
  workflow_dispatch:
    inputs:
      baseUser:
        description: Base user/org
        required: true
        default: dotnet
      baseBranch:
        description: Base branch
        required: true
        default: main
      diffUser:
        description: Diff user/org
        required: true
        default: am11
      diffBranch:
        description: Diff branch
        required: true
        default: main
      uploadArtifacts:
        description: "Upload artifacts (yes: 1, no: 0)"
        required: true
        default: 0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # runs on tag push
      - name: Upload artifacts
        if: ${{ github.event.inputs.uploadArtifacts == '1' }}
        run: |
          git clone https://${{ secrets.CLONE_TOKEN }}:x-oauth-basic@github.com/${{ github.repository }}.git repo
          cd repo
          echo 1
          mkdir -p /tmp/jit-diffs
          echo 2
          echo foo > /tmp/jit-diffs/foo.txt
          echo 3
          tar czf jit-diffs.tar.gz -C /tmp jit-diffs
          echo 4
          artifacts="-a ./jit-diffs.tar.gz"
          echo 5
          tag_name="jit-diffs_$GITHUB_RUN_ID"
          echo 6
          hub release create $artifacts -m "$tag_name" "$tag_name"
          echo 7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
