name: linux-x64 dotnet-runtime build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Test runtime build
      run: |
        git clone https://github.com/dotnet/runtime --single-branch --depth 1
        cd runtime
        sudo eng/common/native/install-dependencies.sh
        ./build.sh -c Release

    - name: Upload artifacts
      run: |
        sudo apt install -y hub

        # hub(1) requires release to be created inside a git repo
        git clone https://${{ secrets.CLONE_TOKEN }}:x-oauth-basic@github.com/${{ github.repository }}.git repo
        cd repo

        artifacts=" -a ../runtime/artifacts/packages/**/*.tar.gz"
        artifacts+=" -a ../runtime/artifacts/packages/**/*.nupkg"

        tag_name="linux_x64_$GITHUB_RUN_ID"
        hub release create $artifacts -m "$tag_name" "$tag_name"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
