name: linux-x64 dotnet-runtime build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Test runtime build
      run: |
        git clone https://github.com/am11/runtime --single-branch --depth 1 --branch feature/build/linux-x86-clang18-2
        cd runtime
        eng/install-native-dependencies.sh
        ./build.sh -c Release
