name: Main CI Workflow

on:
#  push:
#    branches: '*'
#    tags: '*'

  # enable only on-demand
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Test runtime build
      run: |
        git clone https://github.com/cshung/runtime
        cd runtime
        git checkout public/linux-vxsort
        sudo eng/install-native-dependencies.sh
        ./build.sh clr+libs+packs -c Release
        find artifacts/bin -name crossgen2 | while read file; do ls -lL $file; done
        git checkout HEAD~11
        rm -rf artifacts
        ./build.sh clr+libs+packs -c Release
        find artifacts/bin -name crossgen2 | while read file; do ls -lL $file; done
