name: Main CI Workflow

on:
#  push:
#    branches: '*'
#    tags: '*'

  # enable only on-demand
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Test runtime build
      run: |
        git clone https://github.com/dotnet/runtime --single-branch --depth 1
        docker run --rm -v$(pwd)/runtime:/runtime -e ROOTFS_DIR /crossrootfs/x86 \
          mcr.microsoft.com/dotnet-buildtools/prereqs:cbl-mariner-2.0-cross-x86 \
          /runtime/build.sh --cross -c Release
