name: Main CI Workflow

on:
#  push:
#    branches: '*'
#    tags: '*'

  # enable only on-demand
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Install Coverage tool
      run: |
        dotnet tool install --global dotnet-coverage
        throw "This is an error."
        dotnet tool install --global dotnet-coverage
