name: random testing

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          sudo apt update
          sudo   apt install   -y  zstd  libvirt-daemon-system   virt-manager qemu-kvm qemu-system-arm qemu-efi-riscv64 libosinfo-bin  axel expect screen sshpass
          find /usr/share
