name: win-x86 dotnet-runtime build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Test runtime build
      run: |
        cd c:\temp
        git clone https://github.com/am11/runtime --single-branch --depth 1 --branch feature/fcalls-cleanups-3
        cd runtime
        ./build.cmd -arch x86 -cross -s clr+libs
        try {
          ./dotnet.cmd build -t:Test src/libraries/System.Runtime/tests/System.Runtime.Tests -p:xunitoptions="-method System.Tests.UInt64Tests_GenericMath.op_CheckedDivisionTest"
        } catch {
          Get-Content C:\temp\DivUInt64Internal.log
          throw $_
        }
